### ISSUE TITLE
multiple issues with related reading section

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#80]
@rudietuesdays @harumhelmy Just seeing several issues with the related reading section on pages. When you click a link to an item listed under related reading, it now triggers a 404 error. It also looks like those items don't show up on certain page types. For example, the disinformation page should show two items, but only shows one. 
<img width="880" alt="Screen Shot 2022-02-02 at 3 20 59 PM" src="https://user-images.githubusercontent.com/9727494/152231415-b2030dd5-8538-40ee-b1e1-78b5c19b6376.png">

Company pages for Facebook and Google, don't seem to show any of them nor the country pages (U.S. page should show one article). Just to clarify, these are recoding.tech articles I've written and added under related commentary and analysis in the CMS. This actually quite confusing in the CMS right now as there is also a related reading component that now seems to feed into the headlines and highlights section on each page type.  

![Screen Shot 2022-02-02 at 3 21 10 PM](https://user-images.githubusercontent.com/9727494/152231439-e8b44676-8273-4494-9b95-812ba60e2435.png)

**Comment by harumhelmy** [comment]
Hi @gt150! I've just pushed a fix for this. All Related Reading/Commentary & Analysis should show up in their respective topic pages now and be clickable to boot! Sorry about that. 

I've also removed the extraneous "Related Reading" input in the CMS -- I think that was left there because of a confusion on our part on whether "Related Reading"s should be all articles you've written or should also include citations. Moving forward, you can only add your own/Recoding articles to the "Related commentary & analysis" input.  

Related citations will show up on the sidebar under "Latest Headlines" after @jheretic fixes that script.

**Comment by gt150** [comment]
@harumhelmy awesome thanks. Can ask for one more small change related to this widget. Is it possible to change the text under the title to: Our latest thinking about X

**Comment by rudietuesdays** [comment]
Just pushed the updated language change! Also confirming that this is related to #23 and can close both out if fixed?

**Comment by gt150** [comment]
@rudietuesdays you can close this one, but #23 is the section that needs to pull from the citation database and is still not working. My understanding is the Josh is working on fixing this.

**Comment by rudietuesdays** [comment]
@gt150 Got it. To confirm, both this section and the sidebar section (that's been removed) should be on the website and both should pull both articles and citations?

**Comment by gt150** [comment]
@rudietuesdays  The 'related reading' section on the bottom page is only for recoding.tech articles that I've written.  That is now working as intended. The sidebar "Headlines and highlights" should only pull from the citations database.
