### ISSUE TITLE
can we change "country" to "government"?

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#83]
How difficult would it be to change the identifier "Country" to "Region."? I don't know why, but it didn't click with me that listing the EU as a country is quite problematic. I really just need this on the output of the website (so reflected on the menu, country pages, and the law and regulation tracker), if it still shows up in the CMS forms that's fine.

**Comment by gt150** [comment]
@harumhelmy@rae is this something that is an easy fix?

**Comment by jheretic** [comment]
@gt150 is it alright if the URL still includes the path `/countries`? We have a lot of logic that builds URLs based on the page type, so if we need to change it in the URL then we'll either need to modify the structure of the live database to rename it on the backend and throughout the codebase, or add a bunch of special cases everywhere URLs are handled so that it handles 'country' URLs differently than everything else. Either one would is doable but would take a while to do. Otherwise if we just change the text in the menu and the page header that's completely trivial.

Also to clarify, do you want 'government' or 'region'? the issue title says one and the issue description says another.

**Comment by gt150** [comment]
@jheretic for now its fine to keep the path countries for ease. Let's change the text to 'government.' Thanks!

**Comment by gt150** [comment]
@jheretic this works on the menu, but at the top of each government page it still says country? Can we fix that?

**Comment by rudietuesdays** [comment]
Temporary fix pushed to the test site!

**Comment by gt150** [comment]
@rudietuesdays is this on the dev site? I still see 'country' at the top of each page. 
<img width="1335" alt="Screen Shot 2022-02-25 at 11 53 55 AM" src="https://user-images.githubusercontent.com/9727494/155755246-32b15726-eba5-4134-af0c-ff13dd1ff9d7.png">

**Comment by harumhelmy** [comment]
Ah, we weren't clear! The test site is now https://test.recoding.tech -- try https://test.recoding.tech/country/germany

**Comment by gt150** [comment]
@harumhelmy yep, didn't know we'd moved to a new test site. Looks like a good temporary fix. thanks.

**Comment by gt150** [comment]
@harumhelmy I'm still not seeing the changes to this on the live site.
<img width="1364" alt="Screen Shot 2022-03-01 at 11 41 47 AM" src="https://user-images.githubusercontent.com/9727494/156210920-6b17243e-6b61-423c-819c-724f2ef9143f.png">

**Comment by harumhelmy** [comment]
@gt150 Ah yes sorry about that! There's some changes that's still on the `test` branch that we haven't moved to `master`/production yet because of pending style reviews. We should be able to merge it tomorrow, though!
